### ISSUE TITLE
Incentivize Member Participation/Turnout

### ISSUE THREAD

**Issue by 4meta5** [web3garden/sunshine-node#8]
Participation in digital organizations is generally very low without proper incentive alignment. We do **NOT** want this fund coordination DAO to turn into a buy and hold hedge fund that fosters tax aversion by distributing responsibility among a loose organization. Therefore, we need to consider both positive (reward-based) and negative (punishment-based) incentive mechanisms to galvanize DAO members into consistent participation. 

It would be cool to provide multiple options and allow anyone to choose which one works for their project with custom parameterization upon initial configuration #11

**Comment by AmarRSingh** [comment]
Actually, we also need to reconsider the fee structure. In the original [MolochDAO](https://github.com/MolochVentures/moloch/blob/master/flatten/Moloch.sol), the processer fee is taken from the Proposal Bond (given by the proposer). So, **there is a financial disincentive to sponsor proposals**. 

## Criteria for Better Fee Structure
1. Incentivize the sponsorship of proposals that pass (lead to share issuance)
2. Incentivize the processing of proposals (that pass and don't pass)

*Where should this money come from?* The naive solution would seem to be taking some percentage of `proposal.tokenTribute` which is what I initially did, but that assumes every application contains a tokenTribute (and grant applications do not stake tokens!) What else can we do to cover these costs and align incentives properly?
* Share dilution of other members? I feel like that's hiding the costs to DAO members. We could pursue this if costs of dilution are communicated effectively to members, but it feels off (especially because we're already diluting shares in the event of a passed proposal).

## Insurance Pool Proposal
We could transfer the `proposal_bond` given by the proposer to a new subpool of `Pool` called `{insurance: AccountId}` if the proposal doesn't pass. Then, use this insurance pool to fund (1) and (2). This assumes that rewards will only be available if some other proposals don't pass.

Specifically, if the proposal is processed and fails, the `proposal_bond` could be split between sending to `insurance 

### Fears
Additional complexity exacerbates formalization which creates barriers to entry and ostracizes certain classes of users. Laura Kalbag has talked about this, but I can't find it -- [this talk of hers](https://noti.st/laurakalbag/ESaCQp/sabotaging-our-future-selves) is tangentially relevant.

Also, it becomes difficult to model/predict incentives when we add this complexity. See https://github.com/AmarRSingh/MoloChameleon/issues/4 https://github.com/AmarRSingh/MoloChameleon/issues/10

**Comment by AmarRSingh** [comment]
## Floating Proposal Bond
Maybe the proposal bond should depend on (1) if a tokenTribute is offered with the given proposal (2) the number of shares requested vs the total number of existing shares (3) Within the proposalQ, \sum{shares_requested} and \sum{tokenTributes}

The hard part is really identifying bribery (*coercion*) attack vectors that could be inadvertently opened by dynamic parameterization.

**Comment by AmarRSingh** [comment]
## Charging Rent for Non-Active Members

i.e. a tax on share ownership over time that increases in proportion to inactivity

**Comment by AmarRSingh** [comment]
By burning a member's shares, we are redistributing those funds to all the other members; **how we present these mechanisms matters**...

**Comment by 4meta5** [comment]
some interesting thoughts, this is now irrelevant
